"""Build verification: BPF objects, skeleton, loader linkage against the kernel-headers libbpf 1.4 (never the
system libbpf 0.5), CO-RE relocations against the running kernel's BTF. Unprivileged: nothing is loaded."""

import json
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from ._replay import BPF_OBJ, BPFTOOL, BUILD, EBPF, LOADER, REPLAY, SKEL, ensure_built

LIBBPF_DIR = Path("/usr/src/linux-headers-6.8.0-138-generic/tools/bpf/resolve_btfids/libbpf")
SYSTEM_LIBBPF = Path("/usr/lib/x86_64-linux-gnu/libbpf.so.0.5.0")
PROGRAMS = {"sn_sched_wakeup": "tp_btf/sched_wakeup", "sn_sched_wakeup_new": "tp_btf/sched_wakeup_new",
            "sn_sched_switch": "tp_btf/sched_switch", "sn_softirq_entry": "tp_btf/softirq_entry",
            "sn_softirq_exit": "tp_btf/softirq_exit", "sn_tcp_retransmit_skb": "tp_btf/tcp_retransmit_skb",
            "sn_kfree_skb": "tp_btf/kfree_skb"}
# BPF_MAP_TYPE: 2 ARRAY (.rodata), 6 PERCPU_ARRAY, 9 LRU_HASH
MAPS = {"sn_wake": (9, 16384), "sn_hist": (6, 1), "sn_stats": (6, 22), "sn_sirq_start": (6, 1),
        "sn_sirq_acc": (6, 10), "sn_retrans": (6, 1), "sn_kfree": (6, 129), "sentinel.rodata": (2, 1)}


def run(argv, **kw):
    return subprocess.run(argv, capture_output=True, text=True, timeout=600, **kw)


def setUpModule():
    ensure_built()


class TestArtifacts(unittest.TestCase):
    def test_all_artifacts_built(self):
        for p in (BUILD / "vmlinux.h", BPF_OBJ, SKEL, LOADER, REPLAY, BUILD / "min_core.btf"):
            with self.subTest(p=p.name):
                self.assertTrue(p.is_file() and p.stat().st_size > 0)

    def test_bpf_object_programs_and_sections(self):
        out = run(["readelf", "-SW", str(BPF_OBJ)]).stdout
        self.assertEqual(sorted(re.findall(r"\] (tp_btf/\S+)\s+PROGBITS", out)), sorted(PROGRAMS.values()))
        for sec in (".BTF", ".BTF.ext", ".maps", ".rodata", "license"):
            self.assertRegex(out, rf"\] {re.escape(sec)}\s")
        self.assertIn("EM_BPF", run(["readelf", "-h", str(BPF_OBJ)]).stdout.replace("Linux BPF", "EM_BPF"))

    def test_check_open_programs_and_bounded_maps(self):
        """libbpf 1.4 opens the embedded object (ELF + BTF) with no bpf() syscall; every map is fixed-size."""
        d = json.loads(run([str(LOADER), "--check-open"]).stdout)
        self.assertEqual(dict(d["programs"]), PROGRAMS)
        self.assertEqual({n: (t, e) for n, t, e in d["maps"]}, MAPS)

    def test_skeleton_matches_object(self):
        text = SKEL.read_text()
        self.assertIn("THIS FILE IS AUTOGENERATED BY BPFTOOL", text)
        for name in list(PROGRAMS) + [m for m in MAPS if not m.startswith("sentinel.")]:
            self.assertRegex(text, rf"\b{name}\b")
        self.assertIn("struct sn_cfg sn_cfg;", text)                            # rodata configuration exposed

    def test_core_relocations_resolve_against_running_kernel(self):
        """bpftool computed the minimal BTF that the object's CO-RE relocations need from /sys/kernel/btf/vmlinux:
        every field the programs read was found in the running kernel."""
        raw = run([BPFTOOL, "btf", "dump", "file", str(BUILD / "min_core.btf"), "format", "raw"]).stdout
        for struct, fields in (("task_struct", ("pid", "cgroups")), ("css_set", ("dfl_cgrp",)),
                               ("cgroup", ("level", "kn", "ancestors")), ("kernfs_node", ("id",)),
                               ("sk_buff", ("sk",)), ("net_device", ("nd_net",)), ("sock_common", ("skc_net",)),
                               ("net", ("ns",)), ("ns_common", ("inum",))):
            block = re.search(rf"STRUCT '{struct}'.*?(?=\n\[|\Z)", raw, re.S)
            with self.subTest(struct=struct):
                self.assertIsNotNone(block)
                for f in fields:
                    self.assertIn(f"'{f}'", block.group(0))
        ext = run(["readelf", "-SW", str(BPF_OBJ)]).stdout
        self.assertRegex(ext, r"\.BTF\.ext")


class TestLibbpfLinkage(unittest.TestCase):
    def test_version_compiled_equals_linked_1_4(self):
        d = json.loads(run([str(LOADER), "--version"]).stdout)
        self.assertEqual((d["libbpf_compiled"], d["libbpf_linked"], d["match"]), ("1.4", "1.4", True))

    def test_no_shared_libbpf_dependency(self):
        for b in (LOADER, REPLAY):
            with self.subTest(b=b.name):
                needed = re.findall(r"\(NEEDED\).*\[(.*)\]", run(["readelf", "-d", str(b)]).stdout)
                self.assertEqual(sorted(needed), ["libc.so.6", "libelf.so.1", "libz.so.1"])
                self.assertNotIn("libbpf", run(["ldd", str(b)]).stdout)

    def test_libbpf_1_4_implementation_is_inside_the_binary(self):
        """The libbpf symbols are defined in the executable (static archive), none left undefined to resolve
        from the system libbpf.so.0.5.0."""
        nm = run(["nm", str(LOADER)]).stdout
        for sym in ("libbpf_major_version", "bpf_object__open_skeleton", "bpf_object__load_skeleton",
                    "btf__load_vmlinux_btf", "bpf_map__lookup_elem"):
            self.assertRegex(nm, rf" T {sym}\n")
        undefined = run(["nm", "-u", str(LOADER)]).stdout
        self.assertNotRegex(undefined, r"\b(bpf_|btf__|libbpf_)")
        # 1.x-only API present in the binary, absent from the system 0.5 library
        self.assertRegex(nm, r" T libbpf_version_string\n")
        if SYSTEM_LIBBPF.exists():
            self.assertNotIn("libbpf_version_string", run(["nm", "-D", str(SYSTEM_LIBBPF)]).stdout)

    def test_build_refuses_wrong_or_missing_libbpf(self):
        cases = {"system headers (0.5: no libbpf_version.h)": ["LIBBPF_INC=/usr/include"],
                 "missing archive": ["LIBBPF_A=/nonexistent/libbpf.a"],
                 "-lbpf requested": ["LDLIBS=-lbpf"],
                 "unexpected version": ["LIBBPF_EXPECT=0.5"],
                 "shared system libbpf by path": [f"LDLIBS={SYSTEM_LIBBPF}"]}
        for name, extra in cases.items():
            with self.subTest(name):
                p = run(["make", "-n", "-C", str(EBPF), "all"] + extra)
                self.assertNotEqual(p.returncode, 0)
                self.assertRegex(p.stderr, r"refusing|must not be|expected")

    def test_disguised_shared_libbpf_is_rejected_after_link(self):
        """Last line of defence: even a shared libbpf under another file name (here a symlink to the system
        0.5.0 library) is detected from the binary's NEEDED entries, and the binary is deleted."""
        if not SYSTEM_LIBBPF.exists():
            self.skipTest("system libbpf not installed")
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "libdisguised.so").symlink_to(SYSTEM_LIBBPF)
            libs = f"-L{d} -ldisguised {LIBBPF_DIR}/libbpf.a -lelf -lz"
            p = run(["make", "-C", str(EBPF), f"BUILD={d}/b", f"HOST_LIBS={libs}", f"{d}/b/sentinel_replay"])
            self.assertNotEqual(p.returncode, 0)
            self.assertIn("needs a shared libbpf", p.stderr)
            self.assertFalse((Path(d) / "b" / "sentinel_replay").exists())

    def test_makefile_uses_explicit_archive_and_never_lbpf(self):
        mk = (EBPF / "Makefile").read_text()
        self.assertIn(f"LIBBPF_DIR  ?= /usr/src/linux-headers-$(KREL)/tools/bpf/resolve_btfids/libbpf", mk)
        self.assertIn("HOST_LIBS   := $(LIBBPF_A) -lelf -lz", mk)
        uses = [l for l in mk.splitlines() if "-lbpf" in l and not l.lstrip().startswith("#")
                and "findstring" not in l and "$(error" not in l]
        self.assertEqual(uses, [])                                   # only the refusal guard names it
        self.assertFalse([l for l in mk.splitlines() if "pkg-config" in l and not l.lstrip().startswith("#")])


class TestNoKernelInteraction(unittest.TestCase):
    """The unprivileged modes used in this phase never issue bpf() or perf_event_open()."""

    def test_no_bpf_syscalls(self):
        strace = shutil.which("strace")
        if strace is None:
            self.skipTest("strace not installed")
        with tempfile.TemporaryDirectory() as d:
            for argv in ([str(LOADER), "--version"], [str(LOADER), "--check-open"],
                         [str(LOADER), "--cgroup-id", "0"],                       # refused before any open
                         [BPFTOOL, "gen", "min_core_btf", "/sys/kernel/btf/vmlinux", f"{d}/m.btf", str(BPF_OBJ)]):
                with self.subTest(argv=argv[1:3]):
                    log = Path(d) / "trace"
                    run([strace, "-f", "-qq", "-e", "trace=bpf,perf_event_open", "-o", str(log)] + argv)
                    self.assertNotRegex(log.read_text(), r"\b(bpf|perf_event_open)\(")

    def test_run_mode_refuses_incomplete_target(self):
        p = run([str(LOADER), "--cgroup-id", "5", "--max-seconds", "1"])
        self.assertEqual(p.returncode, 64)
        self.assertEqual(json.loads(p.stdout.splitlines()[-1]),
                         {"v": 1, "type": "unavailable", "reason": "missing target configuration"})


class TestCleanBuild(unittest.TestCase):
    def test_reproducible_from_scratch(self):
        """A fresh build directory rebuilds everything (vmlinux.h included) and yields the same BPF object."""
        with tempfile.TemporaryDirectory() as d:
            p = run(["make", "-C", str(EBPF), f"BUILD={d}/b", "all"])
            self.assertEqual(p.returncode, 0, p.stderr[-2000:])
            self.assertEqual((Path(d) / "b" / "sentinel.bpf.o").read_bytes(), BPF_OBJ.read_bytes())


if __name__ == "__main__":
    unittest.main()
